=== Reecer9714/proc-gen-data/schema/action.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "action",
  "description": "Schema for actions",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the action",
      "examples": ["Nick", "Stab", "Slash"],
      "default": "filename"
    },
    "cost": {
      "type": "integer",
      "description": "The relative cost of an action. This can be mapped to an AP cost or an enum like free, bonus, action, action+bonus",
      "examples": [0, 1, 2, 3],
      "default": 2,
      "minimum": 0
    },
    "display": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Display strings for the action",
      "examples": [
        "{user.name} nicks {target.name}",
        "{user.name} cuts {target.name}"
      ],
      "default": []
    },
    "target": {
      "$ref": "./target.schema.json#"
    },
    "effects": {
      "$ref": "effect/effects.schema.json#"
    },
    "userEffects": {
      "$ref": "effect/effects.schema.json#"
    },
    "params": {
      "$ref": "components.schema.json#/definitions/params"
    },
    "requires": {
      "type": "array",
      "description": "Requirements for the action",
      "items": {
        "type": "string",
        "pattern": "^(is|condition|item):\\$?[a-zA-Z0-9_\\-]+$"
      },
      "default": []
    }
  }
}

=== Reecer9714/proc-gen-data/data/dnd/action/weapon/strike.json
{
  "name": "Strike",
  "display": [
    "{user.name} strikes {target.name}",
    "{user.name} attacks {target.name}"
  ],
  "cost": 2,
  "target": {
    "$ref": "../component/target.json#/single_melee_enemy"
  },
  "params": {
    "damage_type": "slashing",
    "damage_amount": "1d6"
  },
  "effects": [
    {
      "id": "damage",
      "type": "$damage_type",
      "amount": "$damage_amount"
    }
  ]
}

=== Reecer9714/proc-gen-data/data/dnd/action/weapon/versitile.json
{
  "name": "Versitile Attack",
  "cost": 2,
  "target": {
    "$ref": "../component/target.json#/single_melee_enemy"
  },
  "display": [
    "{user.name} attacks {target.name}",
    "{user.name} strikes {target.name}"
  ],
  "params": {
    "damage_type": "slashing",
    "one_handed_damage": "1d8",
    "two_handed_damage": "1d10"
  },
  "effects": [
    {
      "conditional": ["is:one-handed"],
      "id": "damage",
      "type": "$damage_type",
      "amount": "$one_handed_damage"
    },
    {
      "conditional": ["is:two-handed"],
      "id": "damage",
      "type": "$damage_type",
      "amount": "$two_handed_damage"
    }
  ]
}

=== Reecer9714/proc-gen-data/data/dnd/action/weapon/topple.json
{
  "name": "Topple",
  "cost": 2,
  "display": [
    "{user.name} trips {target.name}",
    "{user.name} knocks {target.name} to the ground"
  ],
  "target": {
    "$ref": "../component/target.json#/single_melee_enemy"
  },
  "effects": [
    {
      "id": "condition",
      "action": "add",
      "type": "prone"
    }
  ]
}

=== Reecer9714/proc-gen-data/data/dnd/action/weapon/nick.json
{
  "name": "Nick",
  "cost": 1,
  "display": [
    "{user.name} nicks {target.name}",
    "{user.name} cuts {target.name}"
  ],
  "target": {
    "$ref": "../component/target.json#/single_melee_enemy"
  },
  "effects": [
    {
      "id": "damage",
      "type": "slashing",
      "amount": 1
    },
    {
      "id": "status",
      "effects": [
        {
          "id": "damage",
          "type": "bleed",
          "display": [
            "{name} is bleeding",
            "{name} bleeds",
            "{name}'s wound bleeds"
          ],
          "amount": "1d4",
          "duration": 2
        }
      ]
    }
  ]
}

=== Reecer9714/proc-gen-data/data/base/action/basic/unarmed.json
{
  "name": "Unarmed",
  "cost": 1,
  "display": [
    "{user.name} punches {target.name}",
    "{user.name} kicks {target.name}",
    "{user.name} slaps {target.name}",
    "{user.name} headbutts {target.name}"
  ],
  "target": {
    "$ref": "../component/target.json#/single_melee_enemy"
  },
  "params": {
    "damage_type": "bludgeoning",
    "damage_amount": 1
  },
  "effects": [
    {
      "id": "damage",
      "type": "$damage_type",
      "amount": "$damage_amount"
    }
  ]
}

=== Reecer9714/proc-gen-data/data/dnd/action/weapon/throw.json
{
  "name": "Throw",
  "cost": 2,
  "display": [
    "{user.name} throws a dagger at {target.name}",
    "{user.name} hurls a dagger at {target.name}"
  ],
  "target": {
    "$ref": "../component/target.json#/single_ranged_enemy"
  },
  "effects": [
    {
      "id": "damage",
      "type": "piercing",
      "amount": "1d4"
    },
    {
      "id": "inventory",
      "action": "remove",
      "item": "$self"
    }
  ]
}
